Use a list comprehension instead of map().
LeastAuthority/kubetop pull request #51
Opened 2018-03-29 04:11 UTC by rodrigc

In Python 3, we cannot do map() + [].

2018-04-18 17:38 UTC, exarkun requested changes
Thanks.  One comment inline.  Also, might be nice to merge in master.

2018-04-18 17:38 UTC, exarkun commented on src/kubetop/_metadata.py
> +version_string = ".".join([str(v) for v in version_tuple] + ["dev0"])
Can you use `list(...)` instead of `[...]` so that the loop variable doesn't leak on Python 2?  Thanks.

2018-04-19 03:45 UTC, rodrigc commented
@exarkun OK, I have replaced the list comprehension with *list(map(.....))*

2018-04-19 12:03 UTC, exarkun commented
Thanks.  Looks good, I'll merge.  Just as a point of clarification, I would also have been okay with:

```
".".join(list(str(v) for v in version_tuple) + ["dev0"])
```

2018-04-19 12:03 UTC, exarkun approved these changes

2018-04-19 12:04 UTC, merged